name: BillyOh
favicon: null
layout_spectrum: 0.3251568905543536
typography_spectrum: 0.5112560342531651
title: BillyOh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d1381d'
    - '#edb4aa'
    - '#494949'
  brandStrength: 0.125
  lightness: 0.0008069463074207306
  saturation: 0.5222173980437219
  rhythmicContrast: 0.46774308010935783
purpose: []
