name: BillyOh
favicon: null
layout_spectrum: 0.2461
typography_spectrum: 0.52259
title: BillyOh - Creating an Ideal Garden Lifestyle for You
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2c2c2c'
    - '#5f5f5f'
    - '#8f8f8f'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
