name: BillyOh
favicon: null
layout_spectrum: 0.3251568905543536
typography_spectrum: 0.5112560342531651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08383762766607106
  lightness: 0.0008069463074207306
  saturation: 0.5222173980437219
  rhythmicContrast: 0.46774308010935783
purpose: []
